### ISSUE TITLE
HuskChat blocks /town chat [toggle]

### ISSUE THREAD

**Issue by Ekmot276** [WiIIiam278/HuskTownsDocs#51] opened 2021-08-22 21:59 UTC
If you have HuskChat and HuskTowns installed together it looks like you cant toggle your town chat using "/town chat". 
Messages will still be send in your Channel selected via HuskChat.

**Comment by WiIIiam278** [comment] 2021-08-22 23:25
Currently going to close this as working as intended; bungee chat plugins including HuskChat are currently incompatible with the toggle feature of town chat. Disable the toggle feature of town chat in config for now. You can still chat using /townchat <msg>

**Closed by WiIIiam278** 2021-08-22 23:25 UTC
